### PR TITLE
Log an error when user has no challenges configured

### LINKED ISSUE #134: Improve error reporting when user has no 2fa methods configured
If a Google Workspace user doesn't have any 2FA methods enabled pam_oslogin_login.so fails with only a Permission Denied without explaining why. In our case we use an external IDP which implements 2FA when authenticating to Google so a lot of users don't have 2FA methods configured on their Google accounts.

I had to resort to strace on my sshd process to figure out that the call to /computeMetadata/v1/oslogin/authenticate/sessions/start returned `status: NO_AVAILABLE_CHALLENGES`. 

I'm going to submit a PR which adds more informative logging in this failure case.

### PR DESCRIPTION
**Pull request by mattiasa**
Improves logging when a user doesn't have any 2FA methods configured for their Google account.

Fixes #134

### CODE REVIEW

**Comment by a-crate** [comment]
@mattiasa Can you sign the CLA for this?

**Comment by mattiasa** [comment]
> @mattiasa Can you sign the CLA for this?

Yes, just trying to get all the legal ducks in line for that.

**Comment by a-crate** [comment]
Leo or Chaitanya can you review as well?
/cc @dorileo  @ChaitanyaKulkarni28

**Comment by dorileo** [comment]
@mattiasa  can you please sign the cla?

**Comment by mattiasa** [comment]
> @mattiasa can you please sign the cla?

We signed the CLA several months ago. Isn't that what the check shows?

**Pull request merged**
