### PR TITLE
continue on error

### PR DESCRIPTION
**Pull request by hopkiw**

### CODE REVIEW

**Comment by hopkiw** [comment]
/hold
want to investigate adding an errnop value for catastrophic failures to disambiguate from parsing of user or group failures. e.g. internal error requesting page 2 of results would mean we write an essentially truncated file

**Comment by hopkiw** [comment]
@illfelder proof of this working is in this PR :)

**Comment by Sarsate** [comment]
LGTM,

Code-wise this looks fine. Behavior-wise, I would be extra careful that this is actually what you want and that you've differentiated the error cases appropriately for when you want best effort vs aborting and have tested them thoroughly.

**Pull request merged**
